### ISSUE TITLE
ISER2016 Lab Tour: Demo on 2016-10-06

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1888]
## Time Schedule

* 2016-10-06 15:30 - 16:20
* (12 min, 10 people) x 4 times

## TODO

- [x] 1. Calibrate intrinsic camera parameter @knorth55 #1886 
- [x] 2. Calibrate extrinsic camera prameter @wkentaro 
- [x] 3. Fix :wait-interpolation-smooth @pazeshun 
- [x] 4. Make the overall demo work @wkentaro 
- [x] 5. Confirmation of 4 @pazeshun
