### ISSUE TITLE
Object segmentation of known objects (dataset + training)

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2028]
# Introduction

Please use below program to create benchmark/training dataset for object segmentation.
Benchmark set is must, but training set can be skipped if the data augmentation/simulation works well using distributed data, Training_items_20170224.
... but I don't expect that.

# TODOs

- [x] Create small dataset (200 images: 150 for train, 50 for valid) (helped by @otsubo @mmurooka, Thanks!)
- [x] Train the network
- [x] Real-time processing
- [ ] Collect more training data for segmentation in clutter (See https://github.com/start-jsk/jsk_apc/issues/2028#issuecomment-289302473)

## 1. Create dataset

**Semi-automated raw data collection**

`baxter@sheeta`

```
roslaunch jsk_2016_01_baxter_apc baxter.launch
roslaunch jsk_2016_01_baxter_apc astra_hand.launch left_first:=true  # maybe false

# pack the shelf bins
roslaunch jsk_arc2017_baxter collect_data_in_bin.launch  # data are saved to ~/.ros/jsk_arc2017_baxter/collect_data_in_bin
```

**Annotation**

Annotation can be done on local pc not on sheeta:

```
$ sshfs -C baxter@sheeta:/home/baxter/.ros/jsk_arc2017_baxter/dataset_jsk_v1 ~/.ros/jsk_arc2017_baxter/dataset_jsk_v1

# ln -s ~/.ros/jsk_arc2017_baxter/dataset_jsk_v1 $(rospack find jsk_arc2017_common)/data/datasets/JSK_V1
rosrun jsk_arc2017_common annotate_dataset_v1.py
```

**Tutorial Movie**
https://drive.google.com/open?id=0B9P1L--7Wd2vNVZPdnpzdllRamc
<a href="https://drive.google.com/open?id=0B9P1L--7Wd2vNVZPdnpzdllRamc"><img width="50%" alt="screen shot 2017-03-17 at 11 03 34" src="https://cloud.githubusercontent.com/assets/4310419/24026003/85b9810e-0b01-11e7-9f54-a3e8eec22b7c.png"></a>

## 3. Real-time processing

https://github.com/start-jsk/jsk_apc/pull/2042#issue-216985453

**Comment by wkentaro** [comment]
@knorth55 @pazeshun 
Currently we have **191 raw images, and 168 annotations**, I use 32 images annotated at APC2016 for training, so 168 + 32 = 200.
The result without in-bin context is not good:

![image](https://cloud.githubusercontent.com/assets/4310419/24333776/3f96f9c8-1299-11e7-8255-d163d8805956.png)

**Comment by wkentaro** [comment]
Stacking data augmentation worked better than expected,

<img src=https://user-images.githubusercontent.com/4310419/27014847-d6e557fa-4f3b-11e7-8372-2b78b8a12b82.png width=70% />

**Comment by wkentaro** [comment]
Moved to https://github.com/start-jsk/jsk_apc/issues/2172 for collection of more data.
